"""Adding column x.

Revision ID: 272361f6e0a2
Revises: 5d8576380b2c
Create Date: 2023-11-24 15:09:11.900611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272361f6e0a2'
down_revision = '5d8576380b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('url', sa.String(length=120), nullable=False))
    op.add_column('entry', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.drop_index('ix_entry_description', table_name='entry')
    op.create_index(op.f('ix_entry_url'), 'entry', ['url'], unique=False)
    op.drop_column('entry', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('description', sa.VARCHAR(length=120), nullable=False))
    op.drop_index(op.f('ix_entry_url'), table_name='entry')
    op.create_index('ix_entry_description', 'entry', ['description'], unique=False)
    op.drop_column('entry', 'last_updated')
    op.drop_column('entry', 'url')
    # ### end Alembic commands ###
