"""empty message

Revision ID: 2f38893b7d2a
Revises: 272361f6e0a2
Create Date: 2023-11-24 16:00:44.322283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f38893b7d2a'
down_revision = '272361f6e0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('last_updated_string', sa.String(length=10000), nullable=True))
    op.drop_column('entry', 'last_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('last_updated', sa.DATETIME(), nullable=True))
    op.drop_column('entry', 'last_updated_string')
    # ### end Alembic commands ###
